"""create counter

Revision ID: 8f667baf6139
Revises: d3e9adef1ae9
Create Date: 2026-08-22 00:14:15.809129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f667baf6139'
down_revision: Union[str, Sequence[str], None] = 'd3e9adef1ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE counter AS BIGINT START WITH 1000 INCREMENT BY 1 MAXVALUE 56800235584")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE counter")
    # ### end Alembic commands ###
